#!/usr/bin/env python3
from __future__ import annotations
import csv,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def check(name,cond): checks.append((name,bool(cond)))
def text(rel): return (ROOT/rel).read_text(encoding='utf-8')
def rows(rel):
    with (ROOT/rel).open(newline='',encoding='utf-8') as f: return list(csv.DictReader(f))
def data(rel): return json.loads(text(rel))
required=['paper/TRACE_TO_SCHEME_EXPORT_THEOREM_v35.tex','paper/G1_G6_APF_DERIVATION_v36.tex','paper/TOP_MSR_SCALE_SELECTION_THEOREM_v37.tex','paper/CHARGED_LEPTON_RESIDUAL_OPERATOR_THEOREM_v38.tex','paper/CHARGED_LEPTON_COEFFICIENT_CLOSURE_THEOREM_v39.tex','paper/CHARGED_LEPTON_TRACE_VECTOR_SOURCE_GATE_AND_QED_CODOMAIN_THEOREM_v40.tex','paper/CHARGED_LEPTON_TRACE_VECTOR_CLOSURE_THEOREM_v41.tex','paper/CHARGED_LEPTON_QED_RESIDUAL_TRANSPORT_WITNESS_v42.tex','paper/CHARGED_LEPTON_QED_SCALAR_NORMALIZATION_AND_COUNT_SOURCE_v43.tex','paper/CHARGED_LEPTON_QED_COVARIANCE_AND_RUNNING_CODOMAIN_THEOREM_v44.tex','paper/CHARGED_LEPTON_QED_RUNNING_TRANSPORT_THEOREM_v45.tex','paper/CHARGED_LEPTON_POLE_COMPLETION_AND_QED_LEDGER_THEOREM_v46.tex','paper/CHARGED_LEPTON_CODATA_LEDGER_AND_LO_QED_TRANSPORT_THEOREM_v47.tex','paper/CHARGED_LEPTON_FULL_QED_RUNNING_LEDGER_AND_COVARIANCE_EVALUATION_v48.tex','paper/CHARGED_LEPTON_QED_CLOSURE_BOUNDARY_THEOREM_v49.tex','tables/charged_lepton_qed_closure_audit_v49.csv','tables/charged_lepton_qed_closure_metrics_v49.csv','tables/charged_lepton_qed_boundary_required_ledger_v49.csv','tables/charged_lepton_qed_forbidden_inputs_v49.csv','tables/trace_to_scheme_case_table_v49.csv','reports/charged_lepton_qed_closure_boundary_summary_v49.md','reports/charged_lepton_qed_closure_boundary_v49_data.json','README_v49.md']
for rel in required: check('exists_'+rel.replace('/','_'),(ROOT/rel).exists())
tex=text('paper/CHARGED_LEPTON_QED_CLOSURE_BOUNDARY_THEOREM_v49.tex'); summary=text('reports/charged_lepton_qed_closure_boundary_summary_v49.md'); readme=text('README_v49.md'); j=data('reports/charged_lepton_qed_closure_boundary_v49_data.json')
metrics={r['lepton']:r for r in rows('tables/charged_lepton_qed_closure_metrics_v49.csv')}; audit={r['layer']:r for r in rows('tables/charged_lepton_qed_closure_audit_v49.csv')}; ledger={r['entry']:r for r in rows('tables/charged_lepton_qed_boundary_required_ledger_v49.csv')}; forbidden={r['forbidden_input']:r for r in rows('tables/charged_lepton_qed_forbidden_inputs_v49.csv')}; case={r['sector']:r for r in rows('tables/trace_to_scheme_case_table_v49.csv')}
alpha_inv=137.035999177; alpha_inv_unc=0.000000021; alpha=1/alpha_inv; alpha_unc=alpha_inv_unc/(alpha_inv**2); aopi=alpha/math.pi; lo_factor=1/(1+aopi); second=100*(aopi**2); third=100*(aopi**3)
phi=[0.5110026357885311,105.658243985342,1776.9168320084111]; refs=[0.51099895069,105.6583755,1776.86]; unc=[0.00000000016,0.0000023,0.12]
absres=[phi[i]-refs[i] for i in range(3)]; rel=[100*absres[i]/refs[i] for i in range(3)]; apf=100/5063; combined=math.sqrt(apf**2+second**2); ratios=[abs(x)/combined for x in rel]; lo_run=[x*lo_factor for x in phi]
for nd in ['Charged-Lepton QED Closure Boundary Theorem','final closure boundary','P_{\\rm full\\ QED\\ ledger\\ boundary}','No-smuggling closure','External-ledger boundary','P_{\\rm QED\\ running\\ final}','not an APF-side missing theorem']:
    check('tex_contains_'+nd[:40].replace(' ','_').replace('\\','bs'), nd in tex)
for nd in ['CHARGED_LEPTON_QED_CLOSURE_BOUNDARY_THEOREM_PASS','P_QED_BRANCH_CLOSED_AT_APF_POLE_PLUS_EXTERNAL_LEDGER_BOUNDARY','max residual / combined envelope','APF_CHARM_TRACE_TO_MSBAR_NORMALIZATION_OR_TRANSPORT_MAP']:
    check('summary_contains_'+nd[:40].replace(' ','_'), nd in summary)
for nd in ['CHARGED_LEPTON_QED_CLOSURE_BOUNDARY_THEOREM_PASS','P_QED_BRANCH_CLOSED_AT_APF_POLE_PLUS_EXTERNAL_LEDGER_BOUNDARY','python scripts/check_charged_lepton_qed_closure_boundary_v49.py']:
    check('readme_contains_'+nd[:40].replace(' ','_'), nd in readme)
check('json_status',j['status']=='CHARGED_LEPTON_QED_CLOSURE_BOUNDARY_THEOREM_PASS'); check('json_package',j['package']=='APF_v49_CHARGED_LEPTON_QED_CLOSURE_BOUNDARY_THEOREM'); check('json_claim',j['closure_claim']=='P_QED_BRANCH_CLOSED_AT_APF_POLE_PLUS_EXTERNAL_LEDGER_BOUNDARY'); check('json_alpha_inv',abs(j['codata_ledger']['alpha_inverse']-alpha_inv)<1e-15); check('json_alpha',abs(j['codata_ledger']['alpha']-alpha)<1e-20); check('json_alpha_unc',abs(j['codata_ledger']['alpha_uncertainty']-alpha_unc)<1e-24); check('json_aopi',abs(j['qed_transport_witness']['alpha_over_pi']-aopi)<1e-20); check('json_lo_factor',abs(j['qed_transport_witness']['LO_factor']-lo_factor)<1e-15); check('json_second',abs(j['qed_transport_witness']['L2_scale_percent']-second)<1e-18); check('json_third',abs(j['qed_transport_witness']['L3_scale_percent']-third)<1e-20); check('json_combined',abs(j['covariance_closure']['combined_envelope_percent']-combined)<1e-18); check('json_inside',j['covariance_closure']['all_inside_combined_envelope'] is True); check('json_next',j['next_theorem']=='APF_CHARM_TRACE_TO_MSBAR_NORMALIZATION_OR_TRANSPORT_MAP')
for i,lab in enumerate(['e','mu','tau']):
    check('json_phi_'+lab,abs(j['pole_route']['Phi_l_v43_MeV'][i]-phi[i])<1e-12); check('json_ref_'+lab,abs(j['codata_ledger']['charged_lepton_reference_MeV'][i]-refs[i])<1e-12); check('json_absres_'+lab,abs(j['pole_route']['absolute_residual_MeV'][i]-absres[i])<1e-12); check('json_rel_'+lab,abs(j['pole_route']['relative_residual_percent'][i]-rel[i])<1e-12); check('json_ratio_'+lab,abs(j['covariance_closure']['residual_over_combined_envelope'][i]-ratios[i])<1e-12); check('json_lo_run_'+lab,abs(j['qed_transport_witness']['LO_running_witness_MeV'][i]-lo_run[i])<1e-12)
    r=metrics[lab]; check('metrics_phi_'+lab,abs(float(r['Phi_v43_MeV'])-phi[i])<1e-12); check('metrics_ref_'+lab,abs(float(r['CODATA2022_reference_MeV'])-refs[i])<1e-12); check('metrics_absres_'+lab,abs(float(r['absolute_residual_MeV'])-absres[i])<1e-12); check('metrics_rel_'+lab,abs(float(r['relative_residual_percent'])-rel[i])<1e-12); check('metrics_apf_'+lab,abs(float(r['APF_envelope_percent'])-apf)<1e-18); check('metrics_qed2_'+lab,abs(float(r['QED_L2_scale_percent'])-second)<1e-18); check('metrics_comb_'+lab,abs(float(r['combined_envelope_percent'])-combined)<1e-18); check('metrics_ratio_'+lab,abs(float(r['residual_over_combined_envelope'])-ratios[i])<1e-12); check('metrics_status_'+lab,r['status']=='inside_v49_closure_envelope')
for layer,status in [('APF_trace_source','P_trace_vector_closed'),('residual_operator','P_operator_and_coefficients_closed'),('pole_completion','P_pole_completion_APF_envelope_CODATA2022'),('LO_QED_transport','P_LO_QED_numeric_witness'),('QED_truncation_covariance','P_QED_truncation_covariance_admitted'),('full_QED_running','P_full_QED_ledger_boundary'),('physical_final','not_claimed')]:
    check('audit_'+layer,layer in audit); check('audit_status_'+layer,audit[layer]['status_after_v49']==status)
for key in ['S_run','mu','L','K_n','threshold_schedule','matching_convention','alpha_running','Sigma_QED']:
    check('ledger_'+key,key in ledger); check('ledger_status_'+key,ledger[key]['v49_status']=='external_required'); check('ledger_guard_'+key,ledger[key]['smuggling_guard']!='')
for key in ['CODATA masses to construct T_l','m_e m_mu m_tau residual ratios as correction factors','target-selected alpha','target-selected scale mu','target-selected loop order','threshold schedule chosen from residuals','least-squares QED cleanup','L>=2 coefficients inferred from residuals']:
    check('forbidden_'+key.replace(' ','_'),key in forbidden); check('forbidden_audit_'+key.replace(' ','_'),forbidden[key]['v49_audit']=='not used')
for sector in ['EW/W','bottom','charged leptons','top','charm']: check('case_'+sector,sector in case)
check('case_charged_status','P_QED_branch_complete_at_APF_pole_plus_external_ledger_boundary' in case['charged leptons']['physical_export_status']); check('case_charm_open','APF_CHARM_TRACE_TO_MSBAR_NORMALIZATION_OR_TRANSPORT_MAP' in case['charm']['first_failed_gate_or_boundary'])
for nc in ['P_QED_RUNNING_FINAL_NOT_CLAIMED','P_physical_final','zero_residual','CODATA_sigma_agreement_for_all_leptons','multi_loop_QED_running_numerical_final']: check('not_claimed_'+nc,nc in j['not_claimed'])
for req in ['S_run','mu','L','K_n','threshold_schedule','matching_convention','alpha_running','Sigma_QED']: check('json_full_ledger_'+req,req in j['full_qed_ledger_required_before_running_final'])
for forb in ['CODATA masses to construct T_l','generation residual ratios as correction factors','target-selected alpha','target-selected scale mu','target-selected loop order','threshold schedule chosen from residuals','least-squares QED cleanup','L>=2 coefficients inferred from residuals']: check('json_forbidden_'+forb.replace(' ','_'),forb in j['forbidden_inputs_not_used'])
inherited=['check_trace_to_scheme_export_v35.py','check_top_msr_scale_selection_v37.py','check_charged_lepton_residual_operator_v38.py','check_charged_lepton_coefficient_closure_v39.py','check_charged_lepton_trace_vector_source_gate_v40.py','check_charged_lepton_trace_vector_closure_v41.py','check_charged_lepton_qed_residual_witness_v42.py','check_charged_lepton_qed_scalar_normalization_v43.py','check_charged_lepton_qed_covariance_running_codomain_v44.py','check_charged_lepton_qed_running_transport_v45.py','check_charged_lepton_pole_completion_qed_ledger_v46.py','check_charged_lepton_codata_ledger_lo_qed_transport_v47.py','check_charged_lepton_full_qed_running_ledger_covariance_v48.py']
for script in inherited: check('inherited_exists_'+script,(ROOT/'scripts'/script).exists())
passed=sum(ok for _,ok in checks); total=len(checks)
for name,ok in checks: print(('PASS' if ok else 'FAIL'),name)
print(f'Total checks: {passed}/{total}')
if passed!=total or total!=j.get('checks_total'): raise SystemExit(1)
print('CHARGED_LEPTON_QED_CLOSURE_BOUNDARY_THEOREM_PASS')
