"""
APF Defect Composition Calculus v1

Status: [P_architecture]

This module extends the Defect-Strata Calculus with a composition law.

Core doctrine:
    APF status classes are generally not closed under composition.

Given two candidate structures X and Y, composition obeys the schematic law

    Delta_i(X ⊗ Y)
      = Delta_i(X) + Delta_i(Y) + Omega_i(X,Y) - S_i(X,Y)

where:
    Omega_i = composition overhead / obstruction
    S_i     = shared-preservation economy

Composition succeeds at a defect channel iff the resulting defect is zero
(or within explicit tolerance). It fails when overhead exceeds shared economy.

This is architecture/math scaffolding only. It does not promote route-local
claims or assert a physical dynamics beyond existing certificates.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping, Any, Optional

try:
    from apf.continuability_preservation_resolution import (
        APFClass,
        ContinuationCertificate,
        DefectVector,
        classify,
    )
except Exception:  # pragma: no cover - standalone fallback
    class APFClass(str, Enum):
        FORMAL = "formal"
        ADMISSIBLE = "A_Gamma"
        PHYSICAL = "P_Gamma"
        OBSERVABLE = "O_Gamma"
        EXPORTED = "E_Gamma_r"

    @dataclass(frozen=True)
    class DefectVector:
        preservation: float = 0.0
        resolution: float = 0.0
        route: float = 0.0
        ledger: float = 0.0
        smuggling: float = 0.0
        def as_dict(self) -> dict[str, float]:
            return {
                "preservation": self.preservation,
                "resolution": self.resolution,
                "route": self.route,
                "ledger": self.ledger,
                "smuggling": self.smuggling,
            }

    @dataclass(frozen=True)
    class ContinuationCertificate:
        name: str
        finite_continuability: bool
        preservation_stability: bool
        ledger_coherence: bool
        resolved_codomain: bool
        route_closed: bool = False
        route: Optional[str] = None
        capacity_cost: Optional[float] = None
        capacity_bound: Optional[float] = None
        obstruction_channels: tuple[str, ...] = field(default_factory=tuple)
        metadata: Mapping[str, Any] = field(default_factory=dict)
        def defects(self) -> DefectVector:
            return DefectVector(
                preservation=0.0 if self.preservation_stability else 1.0,
                resolution=0.0 if self.resolved_codomain else 1.0,
                route=0.0 if self.route_closed else 1.0,
                ledger=0.0 if self.ledger_coherence else 1.0,
                smuggling=1.0 if "smuggling" in self.obstruction_channels else 0.0,
            )

    def classify(cert: ContinuationCertificate, *, tol: float = 0.0) -> APFClass:
        if not cert.finite_continuability:
            return APFClass.FORMAL
        d = cert.defects()
        if d.preservation > tol or d.ledger > tol or d.smuggling > tol:
            return APFClass.ADMISSIBLE
        if d.resolution > tol:
            return APFClass.PHYSICAL
        if d.route > tol:
            return APFClass.OBSERVABLE
        return APFClass.EXPORTED


STATUS = "[P_architecture]"
MARKER = "DEFECT_COMPOSITION_CALCULUS_PASS"

DEFECT_CHANNELS = ("preservation", "resolution", "route", "ledger", "smuggling")


@dataclass(frozen=True)
class CompositionTerms:
    """
    Per-channel composition terms.

    overhead:
        Positive defect generated by composing X with Y.
    shared_economy:
        Positive defect reduction/economy generated by shared structure.
    """
    overhead: Mapping[str, float] = field(default_factory=dict)
    shared_economy: Mapping[str, float] = field(default_factory=dict)

    def value(self, table: Mapping[str, float], channel: str) -> float:
        if channel not in DEFECT_CHANNELS:
            raise KeyError(f"Unknown defect channel {channel!r}")
        value = float(table.get(channel, 0.0))
        if value < 0:
            raise ValueError(f"Composition term {channel} must be nonnegative")
        return value

    def overhead_value(self, channel: str) -> float:
        return self.value(self.overhead, channel)

    def economy_value(self, channel: str) -> float:
        return self.value(self.shared_economy, channel)


@dataclass(frozen=True)
class CompositionCertificate:
    """
    Certificate for a composed APF candidate X tensor_Gamma Y.

    The result certificate is intentionally derived from the composed
    defect vector, rather than assumed.
    """
    left: ContinuationCertificate
    right: ContinuationCertificate
    terms: CompositionTerms
    result_defects: DefectVector
    result_class: APFClass
    status: str = STATUS
    metadata: Mapping[str, Any] = field(default_factory=dict)


def _clamp_defect(value: float, *, floor: float = 0.0) -> float:
    """Defects are nonnegative; shared economy cannot make them negative."""
    return max(floor, value)


def compose_defect_vectors(
    dx: DefectVector,
    dy: DefectVector,
    terms: CompositionTerms,
) -> DefectVector:
    """
    Defect composition law:

        Delta_i(X ⊗ Y)
          = max(0, Delta_i(X)+Delta_i(Y)+Omega_i-S_i)
    """
    x = dx.as_dict()
    y = dy.as_dict()
    result = {}
    for channel in DEFECT_CHANNELS:
        raw = (
            x[channel]
            + y[channel]
            + terms.overhead_value(channel)
            - terms.economy_value(channel)
        )
        result[channel] = _clamp_defect(raw)
    return DefectVector(**result)


def _classify_from_defects(
    *,
    finite_continuability: bool,
    defects: DefectVector,
    tol: float = 0.0,
) -> APFClass:
    """Classify directly from composed defect vector."""
    if not finite_continuability:
        return APFClass.FORMAL
    if defects.preservation > tol or defects.ledger > tol or defects.smuggling > tol:
        return APFClass.ADMISSIBLE
    if defects.resolution > tol:
        return APFClass.PHYSICAL
    if defects.route > tol:
        return APFClass.OBSERVABLE
    return APFClass.EXPORTED


def compose_certificates(
    left: ContinuationCertificate,
    right: ContinuationCertificate,
    terms: CompositionTerms,
    *,
    name: Optional[str] = None,
    tol: float = 0.0,
    metadata: Optional[Mapping[str, Any]] = None,
) -> CompositionCertificate:
    """
    Compose two candidate structures.

    Finite continuability of the result requires finite continuability of both
    components. The composed APF class is then determined by the composed defects.
    """
    finite = bool(left.finite_continuability and right.finite_continuability)
    result_defects = compose_defect_vectors(left.defects(), right.defects(), terms)
    result_class = _classify_from_defects(
        finite_continuability=finite,
        defects=result_defects,
        tol=tol,
    )
    merged_meta = dict(metadata or {})
    if name is not None:
        merged_meta["name"] = name
    return CompositionCertificate(
        left=left,
        right=right,
        terms=terms,
        result_defects=result_defects,
        result_class=result_class,
        metadata=merged_meta,
    )


def composition_closed_at_channel(
    comp: CompositionCertificate,
    channel: str,
    *,
    tol: float = 0.0,
) -> bool:
    """True iff composed defect vanishes in the selected channel."""
    defects = comp.result_defects.as_dict()
    if channel not in defects:
        raise KeyError(f"Unknown defect channel {channel!r}")
    return defects[channel] <= tol


def composition_preservation_closed(comp: CompositionCertificate, *, tol: float = 0.0) -> bool:
    return composition_closed_at_channel(comp, "preservation", tol=tol)


def composition_resolution_closed(comp: CompositionCertificate, *, tol: float = 0.0) -> bool:
    return composition_closed_at_channel(comp, "resolution", tol=tol)


def composition_route_closed(comp: CompositionCertificate, *, tol: float = 0.0) -> bool:
    return composition_closed_at_channel(comp, "route", tol=tol)


def overhead_dominates(terms: CompositionTerms, channel: str) -> bool:
    """True when composition overhead exceeds shared economy."""
    return terms.overhead_value(channel) > terms.economy_value(channel)


def economy_balances(terms: CompositionTerms, channel: str) -> bool:
    """True when shared economy exactly balances overhead."""
    return terms.overhead_value(channel) == terms.economy_value(channel)


def economy_exceeds(terms: CompositionTerms, channel: str) -> bool:
    """True when shared economy more than offsets overhead."""
    return terms.economy_value(channel) > terms.overhead_value(channel)


def nonclosure_witness(
    left: ContinuationCertificate,
    right: ContinuationCertificate,
    terms: CompositionTerms,
    *,
    channel: str = "preservation",
) -> bool:
    """
    Witness that two individually closed/zero-defect objects fail to compose
    at a selected channel.
    """
    comp = compose_certificates(left, right, terms)
    left_zero = left.defects().as_dict()[channel] == 0.0
    right_zero = right.defects().as_dict()[channel] == 0.0
    result_nonzero = comp.result_defects.as_dict()[channel] > 0.0
    return left_zero and right_zero and result_nonzero


def contextuality_as_composition_defect(terms: CompositionTerms) -> bool:
    """
    Architecture-level contextuality witness:
    global composition overhead in preservation/resolution cannot be absorbed.
    """
    return overhead_dominates(terms, "preservation") or overhead_dominates(terms, "resolution")


def route_composition_as_zero_export_defect(comp: CompositionCertificate, *, tol: float = 0.0) -> bool:
    """
    Route composition closes only when the composed route defect vanishes and
    no smuggling defect is introduced.
    """
    return comp.result_defects.route <= tol and comp.result_defects.smuggling <= tol


def horizon_as_external_composition_failure(terms: CompositionTerms) -> bool:
    """
    Horizon-like external failure:
    resolution overhead dominates shared economy at an observer/exterior boundary.
    """
    return overhead_dominates(terms, "resolution")


def perturbative_saturation_indicator(
    number_of_modes: int,
    per_mode_overhead: float,
    shared_economy_total: float,
) -> float:
    """
    Minimal cumulative overhead indicator for perturbative composition.

        max(0, N * overhead_per_mode - shared_economy_total)

    Positive value indicates unresolved cumulative composition burden.
    """
    if number_of_modes < 0:
        raise ValueError("number_of_modes must be nonnegative")
    if per_mode_overhead < 0 or shared_economy_total < 0:
        raise ValueError("overhead/economy inputs must be nonnegative")
    return max(0.0, number_of_modes * per_mode_overhead - shared_economy_total)


def composition_theorem_statement() -> str:
    return (
        "Defect Composition Theorem: APF status classes are not generally "
        "closed under composition. For each defect channel i, composed defect "
        "equals component defects plus composition overhead minus shared economy, "
        "clamped at zero. Composition succeeds only when the relevant composed "
        "defect vanishes. This is architecture-level and does not promote "
        "route-local physical claims."
    )


def bank_marker() -> str:
    return MARKER
