"""When a composite contains the entangled identity carrier, and the colour record that is one.

WHAT THIS ADDS, AGAINST THE PRIOR ART (read this first).

purification_carrier_identities.py (v24.3.449) banks the algebra DOWNSTREAM of
the entangled identity carrier |Omega> = sum_i |i>|i>: the local marginal is
the load, the overlap is Tr(b* b), a local effect gives the sandwich,
right-unitary freedom acts on the reference leg, the carrier's marginal is
full support.  Those are exact and are not in question.  What no module
computes is WHEN A COMPOSITE CONTAINS THE CARRIER AT ALL.  This module
computes that, exactly, and then identifies one banked object that is a
carrier.

  THE BOUNDARY.  Let A, B be subspaces of M_n carried by the commuting local
  subsystem embeddings a -> a (x) I and b -> I (x) b, generating the composite
  C = A (x) B.  Then

      rho_Omega = |Omega><Omega| / n  lies in  C   <=>   A = B = M_n.

  PROOF OF RECORD (two lines, general in n; what executes is the support
  computation and the enumeration).  |Omega><Omega| = sum_{ij} E_ij (x) E_ij.
  For a tensor T in V (x) W and subspaces A <= V, B <= W, T lies in A (x) B
  exactly when the left support of T -- the span of the slices
  (id (x) phi)(T) over functionals phi -- lies in A, and dually on the right.
  The left support of sum_{ij} E_ij (x) E_ij is span{E_ij} = M_n, and likewise
  on the right.  So membership forces A = B = M_n; the converse is immediate.
  The slice/support characterization of membership in a tensor product of
  subspaces is the ONE standard fact used, and it is named here rather than
  smuggled.

  THE HYPOTHESIS IS WEAKER THAN A READER WILL EXPECT, and this was established
  against the module rather than by it: a blinded auditor observed that the
  argument never uses multiplication, so the boundary holds for ARBITRARY
  SUBSPACES A, B <= M_n, not only for *-subalgebras.  The enumeration below
  therefore includes subspaces that are not algebras at all, and they obey the
  same boundary.

  WHAT IT MEANS, STATED CAREFULLY.  Carrying the carrier is not a property a
  composite can have partially.  It requires both local algebras to be the
  FULL matrix algebra -- a saturation condition, of the family
  quantum_frontend_closure.py already carries as un-discharged leaves
  (ALL_POSITIVE_EFFECTS_REALIZABLE, ALL_DENSITIES_PREPARABLE,
  ALL_POVMS_IMPLEMENTABLE, ALL_COMPATIBLE_CP_MAPS_REALIZABLE).  Nothing here
  says whether any physical premise supplies that condition; that question is
  chartered separately and is NOT answered in this module.

  THE COLOUR RECORD IS A CARRIER.  gauge_invariant_record.py banks that the
  unique sharp gauge-invariant record in SU(N) fundamental (x) antifundamental
  is the colour singlet.  Its projector IS rho_Omega, at N = 2, 3, 4, and the
  gauge action of record g (x) I + I (x) conj(g) puts the CONJUGATE on the
  reference leg -- computed here to be load-bearing, since the non-conjugated
  action fails to fix the record on exactly the imaginary generator family.
  That is an identification of a banked object, at reading grade, at ONE
  physical interface.  It is not a generic system-plus-reference carrier and
  is not offered as one.

WHAT AN EARLIER DRAFT GOT WRONG, RECORDED SO IT IS NOT RE-WALKED.  A previous
version diagnosed carrier-admission as turning on NON-ABELIANNESS of the
composite.  That is FALSE, and two blinded auditors killed it with explicit
models: M_2 (x) D_2 at n = 2 is non-abelian, and M_2 (+) C at n = 3 is
non-abelian in both factors, and neither contains the carrier.  Both are
carried below as NAMED ROWS so the refutation executes rather than being
remembered.  The same draft claimed a shared abelian/non-abelian
"discriminator" tying this to the colour sector; that is WITHDRAWN, because
the colour module's abelian control is BASIS ALIGNMENT rather than
abelianness -- its U(1) generator is diagonal, and an abelian subgroup
generated by a non-diagonal generator does not fix the product record.

============================================================================
STATEMENTS

check_L_identity_carrier_membership_boundary (tier 3, [P_math]).
  The boundary, with the load-bearing step of the proof executed: the
  carrier's supports are computed to be all of M_n, which is what forces
  A = B = M_n.  The membership predicate is then evaluated over a declared
  family at n = 2, 3, 4 -- including three subspaces that are NOT algebras --
  and agrees with the boundary on every row.  Maximality is COMPUTED from the
  dimension, never read off the label, and the family is pinned by content
  (dimension and abelianness against a frozen table) rather than by length.
  dim(A (x) B) = dim(A)*dim(B) is computed on every row.  The rank routine is
  tested DIRECTLY against dense inputs of known rank, including a complex one,
  because every spanning set used here is a sparse basis of matrix units on
  which column-counting and elimination agree.
  SCOPED COROLLARY: for a MAXIMAL abelian reference algebra the conditional
  expectation of the carrier is the classical-classical state
  sum_k (1/n) E_kk (x) E_kk, exhibited separably.  The scope is exact and the
  fence is executed: for a NON-maximal abelian reference the same formula
  returns the carrier unchanged, so the corollary is false outside its scope
  and says so in code.

check_L_colour_record_is_the_identity_carrier (tier 3,
  [P_structural_reading | gauge-invariant = physical record, inherited]).
  The identification.  The transcribed singlet projector is pinned
  STRUCTURALLY (support pattern and entry value) against the published form
  before being compared to an independently constructed carrier.  DISCLOSED:
  that pin catches a wrong pattern or a wrong normalization, but CANNOT
  distinguish a faithful transcription from a delegation to the carrier
  constructor, because the two objects coincide -- which is the result.  Both marginals are I/N.  The gauge
  action is checked to be non-zero and generator-dependent; the singlet is
  ANNIHILATED (not merely commuted with) by every generator; a state that is
  NOT annihilated is exhibited; and the conjugated and non-conjugated actions
  travel through ONE code path with a flag, with the failure set computed
  SET-EXACTLY against the imaginary generator family in both directions.

============================================================================
MAY-NOT-CITE.

  - "The bridge is closed" or "the carrier is derived from A1."  Neither is
    shown.  This module says WHEN a composite contains the carrier; it says
    nothing about which composites physics supplies.
  - "The named CP-soundness premises entail / fail to entail the carrier."
    NOT IN THIS MODULE.  An earlier draft carried that claim; it was reduced
    by a blinded audit on two counts -- the premise inventory was
    misidentified (orientation synchronization belongs to
    T_composite_tensor_quotient, not to check_T_same_type_reference_chosen_cp,
    whose fourth premise is independently_maintained_same_type_reference and
    was never formalized) and the banked premise wording carries "FULL" Choi
    corner, under which the countermodel does not run.  The restated result is
    chartered separately and is not banked anywhere.
  - "Non-abelianness is the missing condition" / "commutativity is the
    obstruction."  FALSE, refuted in-check by two named rows.
  - "Two lanes, one discriminator" or any abelian/non-abelian link between
    this boundary and the colour sector.  WITHDRAWN.
  - "Colour supplies the Born carrier" / "the colour record is the generic
    carrier."  One physical interface, at reading grade.
  - "The colour singlet is maximally entangled" as a NEW result.  It is not:
    gauge_invariant_record.py already records the Schmidt rank.  What is new
    is the identification of that object with rho_Omega.
  - "Born is derived" / "P1 or P2 is discharged or reduced."  Standing bars.
  - "The theorem is deep."  The proof is two lines and the hypothesis is
    weaker than stated in the first draft.  The content is the boundary being
    ALL-OR-NOTHING, not the difficulty of proving it.

STANDARD IMPORTS, NAMED: the slice/support characterization of membership in
a tensor product of subspaces (proof of record in this header); the Schmidt
decomposition, for reading a flat reduced spectrum as MAXIMAL entanglement;
Peres 1996 (NPT => entangled), used only in the scoped corollary.

NON-EXPORTING.  physical_premises_certified = false.  No existing grade moved.
"""

from fractions import Fraction as F
from typing import Callable, Dict, List, Sequence, Tuple

PHYSICAL_PREMISES_CERTIFIED = False
EXPORTS: Tuple[str, ...] = ()
BANK_MODIFIED = False

Q = Tuple[F, F]
Mat = List[List[Q]]

_Z: Q = (F(0), F(0))
_ONE: Q = (F(1), F(0))
_I: Q = (F(0), F(1))


def _q(a, b=0) -> Q:
    return (F(a), F(b))


def _add(x: Q, y: Q) -> Q:
    return (x[0] + y[0], x[1] + y[1])


def _sub(x: Q, y: Q) -> Q:
    return (x[0] - y[0], x[1] - y[1])


def _mul(x: Q, y: Q) -> Q:
    return (x[0] * y[0] - x[1] * y[1], x[0] * y[1] + x[1] * y[0])


def _conj(x: Q) -> Q:
    return (x[0], -x[1])


def _neg(x: Q) -> Q:
    return (-x[0], -x[1])


def _isz(x: Q) -> bool:
    return x[0] == 0 and x[1] == 0


def _zeros(n: int, m: int = None) -> Mat:
    m = n if m is None else m
    return [[_Z for _ in range(m)] for _ in range(n)]


def _eye(n: int) -> Mat:
    a = _zeros(n)
    for i in range(n):
        a[i][i] = _ONE
    return a


def _unit(i: int, j: int, n: int) -> Mat:
    a = _zeros(n)
    a[i][j] = _ONE
    return a


def _mm(a: Mat, b: Mat) -> Mat:
    n, k, m = len(a), len(b), len(b[0])
    c = _zeros(n, m)
    for i in range(n):
        for j in range(m):
            s = _Z
            for t in range(k):
                s = _add(s, _mul(a[i][t], b[t][j]))
            c[i][j] = s
    return c


def _mv(a: Mat, v: Sequence[Q]) -> List[Q]:
    out = []
    for i in range(len(a)):
        s = _Z
        for j in range(len(v)):
            s = _add(s, _mul(a[i][j], v[j]))
        out.append(s)
    return out


def _dag(a: Mat) -> Mat:
    return [[_conj(a[j][i]) for j in range(len(a))] for i in range(len(a[0]))]


def _conjm(a: Mat) -> Mat:
    return [[_conj(x) for x in r] for r in a]


def _scal(s: Q, a: Mat) -> Mat:
    return [[_mul(s, x) for x in r] for r in a]


def _addm(a: Mat, b: Mat) -> Mat:
    return [[_add(a[i][j], b[i][j]) for j in range(len(a[0]))]
            for i in range(len(a))]


def _subm(a: Mat, b: Mat) -> Mat:
    return [[_sub(a[i][j], b[i][j]) for j in range(len(a[0]))]
            for i in range(len(a))]


def _eqm(a: Mat, b: Mat) -> bool:
    if len(a) != len(b) or len(a[0]) != len(b[0]):
        return False
    return all(a[i][j] == b[i][j]
               for i in range(len(a)) for j in range(len(a[0])))


def _comm(a: Mat, b: Mat) -> Mat:
    return _subm(_mm(a, b), _mm(b, a))


def _iszm(a: Mat) -> bool:
    return all(_isz(a[i][j]) for i in range(len(a)) for j in range(len(a[0])))


def _kron(a: Mat, b: Mat) -> Mat:
    n, m = len(a), len(b)
    c = _zeros(n * m)
    for i in range(n):
        for j in range(n):
            for k in range(m):
                for l in range(m):
                    c[i * m + k][j * m + l] = _mul(a[i][j], b[k][l])
    return c


def _trace(a: Mat) -> Q:
    s = _Z
    for i in range(len(a)):
        s = _add(s, a[i][i])
    return s


def _is_hermitian(a: Mat) -> bool:
    return _eqm(a, _dag(a))


def _flat(a: Mat) -> List[Q]:
    return [a[i][j] for i in range(len(a)) for j in range(len(a[0]))]


def _rank(rows: Sequence[Sequence[Q]]) -> int:
    m = [list(r) for r in rows]
    if not m:
        return 0
    cols = len(m[0])
    rank = 0
    for c in range(cols):
        piv = next((i for i in range(rank, len(m)) if not _isz(m[i][c])), None)
        if piv is None:
            continue
        m[rank], m[piv] = m[piv], m[rank]
        d = m[rank][c][0] ** 2 + m[rank][c][1] ** 2
        inv = (m[rank][c][0] / d, -m[rank][c][1] / d)
        m[rank] = [_mul(inv, x) for x in m[rank]]
        for i in range(len(m)):
            if i != rank and not _isz(m[i][c]):
                f = m[i][c]
                m[i] = [_sub(m[i][j], _mul(f, m[rank][j]))
                        for j in range(cols)]
        rank += 1
    return rank


def _charpoly(a: Mat) -> List[Q]:
    n = len(a)
    cur = [row[:] for row in a]
    cs: List[Q] = [_ONE]
    for k in range(1, n + 1):
        ck = _mul(_q(F(-1, k)), _trace(cur))
        cs.append(ck)
        if k < n:
            t = [row[:] for row in cur]
            for i in range(n):
                t[i][i] = _add(t[i][i], ck)
            cur = _mm(a, t)
    return cs


def _is_psd_hermitian(a: Mat) -> bool:
    """PSD for a HERMITIAN argument, by characteristic-polynomial signs.  The
    criterion is unsound off the Hermitian slice, so Hermiticity is enforced
    by raising rather than by returning False."""
    if not _is_hermitian(a):
        raise AssertionError(
            "_is_psd_hermitian called on a non-Hermitian matrix: the "
            "characteristic-polynomial sign criterion is unsound there")
    cs = _charpoly(a)
    for k in range(1, len(a) + 1):
        if cs[k][1] != 0:
            raise AssertionError(
                "Hermitian matrix produced a non-real charpoly coefficient")
        if ((-1) ** k) * cs[k][0] < 0:
            return False
    return True


def _partial_transpose(r: Mat, n: int) -> Mat:
    """Transpose the SECOND (reference) factor.  Used only in the corollary.

    DISCLOSED, TWO LEVELS.  (1) On every object this module feeds it the
    spectrum is invariant under transposing the first factor instead, so no
    leg distinguishes the two conventions here; the docstring is the record of
    which is intended.  (2) More generally, a GLOBAL relabelling of the two
    tensor legs -- swapping the argument order of _kron everywhere -- is a
    symmetry of this module's own language and is undetectable from inside it,
    since every construction and every assertion would swap together.  What IS
    detected is a LOCALLY wrong leg: the corollary pins its conditional
    expectation against an asymmetric witness on which the reference-leg and
    system-leg maps disagree completely."""
    p = _zeros(n * n)
    for i in range(n):
        for j in range(n):
            for k in range(n):
                for l in range(n):
                    p[i * n + k][j * n + l] = r[i * n + l][j * n + k]
    return p


def _omega_density(n: int) -> Mat:
    """rho_Omega = |Omega><Omega| / n, |Omega> = sum_i |i>|i>."""
    v = [_Z] * (n * n)
    for i in range(n):
        v[i * n + i] = _ONE
    r = [[_mul(v[i], _conj(v[j])) for j in range(n * n)] for i in range(n * n)]
    return _scal(_q(F(1, n)), r)


def _left_slices(t: Mat, n: int) -> List[Mat]:
    """Left support generators: the slices (id (x) phi_{kl})(T)."""
    out = []
    for k in range(n):
        for l in range(n):
            s = _zeros(n)
            for i in range(n):
                for j in range(n):
                    s[i][j] = t[i * n + k][j * n + l]
            out.append(s)
    return out


def _right_slices(t: Mat, n: int) -> List[Mat]:
    out = []
    for k in range(n):
        for l in range(n):
            s = _zeros(n)
            for i in range(n):
                for j in range(n):
                    s[i][j] = t[k * n + i][l * n + j]
            out.append(s)
    return out


# ---- the declared family.  Three entries are NOT algebras, which the
# ---- boundary does not need and which an audit established.
def _alg_scalars(n: int) -> List[Mat]:
    return [_eye(n)]


def _alg_diagonal(n: int) -> List[Mat]:
    return [_unit(i, i, n) for i in range(n)]


def _alg_full(n: int) -> List[Mat]:
    return [_unit(i, j, n) for i in range(n) for j in range(n)]


def _alg_block(n: int) -> List[Mat]:
    """M_2 (+) C inside M_3, M_2 (+) M_2 inside M_4.  Non-abelian in both
    factors -- the n = 3 row is one of the two named auditor rows."""
    if n == 3:
        return ([_unit(i, j, 3) for i in range(2) for j in range(2)]
                + [_unit(2, 2, 3)])
    if n == 4:
        return ([_unit(i, j, 4) for i in range(2) for j in range(2)]
                + [_unit(i, j, 4) for i in range(2, 4) for j in range(2, 4)])
    raise AssertionError("_alg_block is defined only at n = 3 and n = 4")


def _sub_nonunital(n: int) -> List[Mat]:
    """span{E_00} -- NOT unital, and not an algebra with a unit."""
    return [_unit(0, 0, n)]


def _sub_offdiag(n: int) -> List[Mat]:
    """span{E_01, E_10} -- NOT closed under multiplication, so NOT an
    algebra.  The boundary does not care, which is the point."""
    return [_unit(0, 1, n), _unit(1, 0, n)]


_FAMILY: Dict[int, Dict[str, Callable[[int], List[Mat]]]] = {
    2: {'C.I': _alg_scalars, 'D_n': _alg_diagonal, 'M_n': _alg_full,
        'span{E00}': _sub_nonunital, 'span{E01,E10}': _sub_offdiag},
    3: {'C.I': _alg_scalars, 'D_n': _alg_diagonal, 'M_n': _alg_full,
        'M_2(+)C': _alg_block, 'span{E01,E10}': _sub_offdiag},
    4: {'C.I': _alg_scalars, 'D_n': _alg_diagonal, 'M_n': _alg_full,
        'M_2(+)M_2': _alg_block},
}

# Content pins, frozen as literals: label -> (dimension, is_abelian).  The
# family is pinned by CONTENT, not by length -- a length would accept a
# wholesale substitution, which is the .444 lesson.
_FAMILY_PINS: Dict[int, Dict[str, Tuple[int, bool]]] = {
    2: {'C.I': (1, True), 'D_n': (2, True), 'M_n': (4, False),
        'span{E00}': (1, True), 'span{E01,E10}': (2, False)},
    3: {'C.I': (1, True), 'D_n': (3, True), 'M_n': (9, False),
        'M_2(+)C': (5, False), 'span{E01,E10}': (2, False)},
    4: {'C.I': (1, True), 'D_n': (4, True), 'M_n': (16, False),
        'M_2(+)M_2': (8, False)},
}

# The two models a blinded audit used to kill the earlier draft's diagnosis,
# frozen as literals and asserted SET-EXACTLY (a count would accept a
# duplicate and silently drop the stronger n = 3 row).
_AUDITOR_ROWS: Tuple[Tuple[int, str, str], ...] = (
    (2, 'M_n', 'D_n'),
    (3, 'M_2(+)C', 'M_2(+)C'),
)


def _is_abelian(gens: Sequence[Mat]) -> bool:
    return all(_iszm(_comm(a, b)) for a in gens for b in gens)


def _result(name, epistemic, key_result, evidence, fails, tier,
            dependencies, premises, negative_controls, cross_refs,
            leg_count, expected_legs):
    """Build the result dict and cross-assert THREE independently maintained
    records: the failure list, an independent failure counter, and the number
    of legs actually EXECUTED against a frozen contract.

    The executed-leg count exists because `ck` is a single funnel shared by
    every leg of every check here, so replacing it with a no-op would silence
    hundreds of assertions in one line while both failure records stayed
    consistent at zero.  A neutered funnel reports zero executed legs and is
    caught.  The contract is set-exact by design: adding or removing a leg is
    MEANT to break it.

    RESIDUAL LIMIT, DISCLOSED AND VERIFIED TO BE REAL: an edit that clears all
    three records together, or that substitutes the returned 'passed' literal,
    is NOT caught.  This was demonstrated against this module, not assumed.
    No module can defend against an edit to its own return statement."""
    counted = leg_count[0]
    executed = leg_count[1]
    if len(fails) != counted:
        raise AssertionError(
            f"{name}: failure records disagree -- fail_reasons has "
            f"{len(fails)} entries, the independent counter says {counted}")
    if executed != expected_legs:
        raise AssertionError(
            f"{name}: executed-leg count {executed} does not match the frozen "
            f"contract {expected_legs} -- either a leg was added or removed "
            f"without updating the contract, or the assertion funnel was "
            f"disabled")
    return {
        'fail_count': counted,
        'name': name,
        'epistemic': epistemic,
        'passed': (counted == 0),
        'tier': tier,
        'key_result': key_result,
        'evidence': evidence,
        'fail_reasons': fails,
        'dependencies': list(dependencies),
        'premises': list(premises),
        'negative_controls': list(negative_controls),
        'cross_refs': list(cross_refs),
        'physical_premises_certified': PHYSICAL_PREMISES_CERTIFIED,
        'exports': list(EXPORTS),
        'bank_modified': BANK_MODIFIED,
    }


def _ckr(fails: List[str], counter: List[int]):
    """counter[0] counts FAILURES; counter[1] counts INVOCATIONS."""
    def ck(cond: bool, msg: str) -> None:
        counter[1] += 1
        if not cond:
            fails.append(msg)
            counter[0] += 1
    return ck


_EXPECTED_LEGS: Dict[str, int] = {
    'check_L_identity_carrier_membership_boundary': 284,
    'check_L_colour_record_is_the_identity_carrier': 53,
}


# ==========================================================================
# CHECK 1 -- the membership boundary.
# ==========================================================================


def check_L_identity_carrier_membership_boundary() -> Dict[str, object]:
    """Tier 3, [P_math].  rho_Omega in A (x) B  <=>  A = B = M_n."""
    _NAME = 'check_L_identity_carrier_membership_boundary'
    fails: List[str] = []
    counter = [0, 0]
    ck = _ckr(fails, counter)

    # (0) The primitives must bite.
    ck(_eqm(_eye(2), _eye(2)), "_eqm must accept equal matrices")
    ck(not _eqm(_eye(2), [[_ONE, _ONE], [_Z, _ONE]]),
       "_eqm must REJECT matrices differing in one entry")
    ck(not _eqm(_eye(2), _eye(3)), "_eqm must reject a shape mismatch")
    ck(_is_psd_hermitian(_eye(2)), "the PSD predicate must accept I")
    ck(not _is_psd_hermitian([[_q(1), _Z], [_Z, _q(-1)]]),
       "the PSD predicate must REJECT a Hermitian negative eigenvalue")
    _nh = False
    try:
        _is_psd_hermitian([[_Z, _ONE], [_Z, _Z]])
    except AssertionError:
        _nh = True
    ck(_nh, "the PSD predicate must REFUSE a non-Hermitian argument")

    # _is_abelian must be controlled in BOTH directions; an audit found the
    # earlier version protected only the direction that could not hurt it.
    ck(_is_abelian(_alg_diagonal(3)), "_is_abelian must accept D_n")
    ck(_is_abelian(_alg_scalars(3)), "_is_abelian must accept C.I")
    ck(not _is_abelian(_alg_full(2)), "_is_abelian must REJECT M_n")

    # (0b) THE RANK ROUTINE, TESTED DIRECTLY on dense inputs of known rank.
    # Every spanning set below is a sparse basis of matrix units, on which
    # column-counting and genuine elimination agree -- so the enumeration
    # cannot by itself detect an over-counting rank routine.
    for rows_in, expected, label in (
            ([[_q(1), _q(1)], [_q(1), _q(1)]], 1, "duplicate rows"),
            ([[_q(1), _q(2)], [_q(2), _q(4)]], 1, "proportional rows"),
            ([[_q(1), _q(0)], [_q(0), _q(1)]], 2, "independent rows"),
            ([[_q(1), _q(1), _q(0)], [_q(0), _q(1), _q(1)],
              [_q(1), _q(0), _q(-1)]], 2, "third row is r1 - r2"),
            ([[_ONE, _I], [_I, _q(-1)]], 1, "complex proportional (i*r1)"),
            ([[_q(0), _q(0)], [_q(0), _q(0)]], 0, "zero matrix")):
        got = _rank(rows_in)
        ck(got == expected,
           f"_rank must return {expected} on '{label}'; got {got}")

    # (1) THE LOAD-BEARING STEP OF THE PROOF, EXECUTED.
    # DISCLOSED: left and right support ranks coincide for every tensor
    # (operator Schmidt rank is left/right symmetric), so these are one
    # number reported twice and are not independent evidence.
    support_rows = []
    for n in (2, 3, 4):
        car = _omega_density(n)
        lrank = _rank([_flat(s) for s in _left_slices(car, n)])
        rrank = _rank([_flat(s) for s in _right_slices(car, n)])
        ck(lrank == n * n,
           f"the carrier's LEFT support must be all of M_n (n^2={n*n}); got "
           f"{lrank} -- this is what forces A = M_n")
        ck(rrank == n * n,
           f"the carrier's RIGHT support must be all of M_n (n^2={n*n}); got "
           f"{rrank}")
        support_rows.append(n)
    ck(set(support_rows) == {2, 3, 4},
       f"the support leg must run at n = 2, 3, 4; got {sorted(support_rows)}")
    ck(_rank([_flat(s) for s in _left_slices(
        _kron([[_ONE, _Z], [_Z, _Z]], [[_ONE, _Z], [_Z, _Z]]), 2)]) == 1,
       "a product state must have a ONE-dimensional support, or the support "
       "routine is not reading the tensor structure")

    # (2) THE FAMILY IS PINNED BY CONTENT, not by length.
    for n in (2, 3, 4):
        ck(set(_FAMILY[n]) == set(_FAMILY_PINS[n]),
           f"the family at n={n} must match its frozen pin table set-exactly")
        for label, fn in _FAMILY[n].items():
            gens = fn(n)
            exp_dim, exp_ab = _FAMILY_PINS[n][label]
            got_dim = _rank([_flat(x) for x in gens])
            ck(got_dim == exp_dim,
               f"family member {label} at n={n} must have dimension "
               f"{exp_dim}; got {got_dim}")
            ck(_is_abelian(gens) == exp_ab,
               f"family member {label} at n={n} must have abelianness "
               f"{exp_ab}")

    # (3) THE ENUMERATION.
    rows: List[Dict[str, object]] = []
    mismatches = 0
    redundant_control_rows = 0
    for n in (2, 3, 4):
        car_flat = _flat(_omega_density(n))
        d = n * n
        for na, fa in _FAMILY[n].items():
            for nb, fb in _FAMILY[n].items():
                ga, gb = fa(n), fb(n)
                dim_a = _rank([_flat(x) for x in ga])
                dim_b = _rank([_flat(x) for x in gb])
                span = [_flat(_kron(a, b)) for a in ga for b in gb]
                dim_c = _rank(span)
                ck(dim_c == dim_a * dim_b,
                   f"dim(A (x) B) must equal dim(A)*dim(B) (n={n}, "
                   f"{na}/{nb}); got {dim_c} vs {dim_a * dim_b}")
                in_c = _rank(span + [car_flat]) == dim_c
                # MAXIMALITY IS COMPUTED FROM THE DIMENSION, never read off
                # the label: a wrong spanning-set function would make the
                # label lie, and a label-based predicate compares a name to a
                # name.
                maximal = (dim_a == n * n and dim_b == n * n)
                ck((na == 'M_n') == (dim_a == n * n),
                   f"the algebra labelled {na} must have the dimension its "
                   f"label claims (n={n}); got {dim_a}")
                if in_c != maximal:
                    mismatches += 1
                ck(in_c == maximal,
                   f"membership must agree with A = B = M_n (n={n}, "
                   f"{na}/{nb}): carrier_in={in_c}, maximal={maximal}")
                if redundant_control_rows < 3 and span:
                    tot = [_Z] * len(span[0])
                    for row in span:
                        tot = [_add(tot[t], row[t]) for t in range(len(row))]
                    red = list(span) + [tot] + [list(span[0])]
                    ck(_rank(red) == dim_c,
                       f"appending the sum and a duplicate must not change "
                       f"the rank (n={n}, {na}/{nb})")
                    redundant_control_rows += 1
                rows.append({'n': n, 'A': na, 'B': nb, 'dim_A': dim_a,
                             'dim_B': dim_b, 'dim_C': dim_c,
                             'carrier_in': in_c, 'maximal': maximal,
                             'A_abelian': _is_abelian(ga),
                             'B_abelian': _is_abelian(gb)})
    ck(mismatches == 0,
       f"the boundary must hold on every enumerated row; {mismatches} "
       f"mismatches")
    ck({r['n'] for r in rows} == {2, 3, 4},
       "the enumeration must cover n = 2, 3, 4")
    ck(redundant_control_rows == 3,
       f"the redundant-rank control must run three times; got "
       f"{redundant_control_rows}")
    # non-algebra subspaces must be present, or the weakened hypothesis is
    # asserted and not exercised
    ck(any(r['A'] == 'span{E01,E10}' for r in rows),
       "the enumeration must include a subspace that is NOT an algebra, or "
       "the claim that the boundary needs no multiplication is untested")

    # (4) THE NAMED AUDITOR ROWS, set-exact and distinct.
    ck(len(set(_AUDITOR_ROWS)) == len(_AUDITOR_ROWS),
       "the named auditor rows must be DISTINCT -- a duplicate would silently "
       "drop the stronger model")
    ck(set(_AUDITOR_ROWS) == {(2, 'M_n', 'D_n'), (3, 'M_2(+)C', 'M_2(+)C')},
       "the named auditor rows must match the frozen literal set exactly")
    for (n, na, nb) in _AUDITOR_ROWS:
        row = next((r for r in rows
                    if r['n'] == n and r['A'] == na and r['B'] == nb), None)
        ck(row is not None,
           f"named auditor row {na}/{nb} at n={n} must be in the enumeration")
        if row is not None:
            ck(row['carrier_in'] is False,
               f"named auditor row {na}/{nb} at n={n} must OMIT the carrier")
            ck(not (row['A_abelian'] and row['B_abelian']),
               f"named auditor row {na}/{nb} at n={n} must be NON-abelian in "
               f"at least one factor -- this is what refutes 'commutativity "
               f"is the obstruction'")

    # (5) COROLLARY, SCOPED TO A MAXIMAL ABELIAN REFERENCE, with the fence
    # EXECUTED: outside that scope the same formula returns the carrier.
    coroll_rows = []
    for n in (2, 3):
        car = _omega_density(n)
        img = _zeros(n * n)
        for k in range(n):
            p = _kron(_eye(n), _unit(k, k, n))
            img = _addm(img, _mm(_mm(p, car), p))
        sep = _zeros(n * n)
        for k in range(n):
            sep = _addm(sep, _scal(_q(F(1, n)),
                                   _kron(_unit(k, k, n), _unit(k, k, n))))
        ck(_eqm(img, sep),
           f"for a MAXIMAL abelian reference the image must equal the "
           f"exhibited classical-classical state (n={n})")
        ck(_is_psd_hermitian(img) and _trace(img) == _ONE,
           f"the image must be a state (n={n})")
        ck(_is_psd_hermitian(_partial_transpose(img, n)),
           f"the image must be PPT, consistent with separability (n={n})")
        ck(not _is_psd_hermitian(_partial_transpose(car, n)),
           f"the carrier must be NPT (n={n}), so the conditional expectation "
           f"genuinely destroys the entanglement")
        # WHICH LEG IS PROJECTED, pinned on an ASYMMETRIC witness.  The
        # carrier is swap-symmetric, so it cannot distinguish the reference-leg
        # conditional expectation from the system-leg one.  On
        # W = E_00 (x) E_01 the two differ completely: the reference-leg map
        # annihilates it, the system-leg map fixes it.
        w_asym = _kron(_unit(0, 0, n), _unit(0, 1, n))
        ref_img = _zeros(n * n)
        sys_img = _zeros(n * n)
        for k in range(n):
            pr = _kron(_eye(n), _unit(k, k, n))
            psys = _kron(_unit(k, k, n), _eye(n))
            ref_img = _addm(ref_img, _mm(_mm(pr, w_asym), pr))
            sys_img = _addm(sys_img, _mm(_mm(psys, w_asym), psys))
        ck(_iszm(ref_img),
           f"LEG PIN: the REFERENCE-leg conditional expectation must "
           f"annihilate E_00 (x) E_01 (n={n})")
        ck(_eqm(sys_img, w_asym),
           f"LEG PIN: the SYSTEM-leg conditional expectation must FIX "
           f"E_00 (x) E_01 (n={n}) -- the two maps are distinguished on an "
           f"asymmetric witness, which the swap-symmetric carrier cannot do")

        # THE FENCE, EXECUTED: a NON-maximal abelian reference (C.I) leaves
        # the carrier untouched, so the corollary is FALSE outside its scope.
        p_triv = _kron(_eye(n), _eye(n))
        img_triv = _mm(_mm(p_triv, car), p_triv)
        ck(_eqm(img_triv, car),
           f"FENCE: with the NON-maximal abelian reference C.I the same "
           f"formula returns the carrier unchanged (n={n}) -- the corollary "
           f"is scoped to MAXIMAL abelian references and is false outside it")
        ck(not _is_psd_hermitian(_partial_transpose(img_triv, n)),
           f"FENCE: and that image is still NPT (n={n})")
        coroll_rows.append(n)
    ck(set(coroll_rows) == {2, 3},
       f"the corollary must run at n = 2, 3; got {sorted(coroll_rows)}")

    return _result(
        _NAME,
        '[P_math]',
        ("THE MEMBERSHIP BOUNDARY IS ALL-OR-NOTHING.  For commuting local "
         "subsystem embeddings a -> a (x) I and b -> I (x) b generating "
         "C = A (x) B, the entangled identity carrier lies in C IF AND ONLY "
         "IF both local algebras are the FULL matrix algebra M_n.  The "
         "load-bearing step of the proof is executed: the carrier's supports "
         "are computed to be all of M_n at n = 2, 3, 4, which is what forces "
         "A = B = M_n.  The enumeration corroborates the boundary on every "
         "row of a declared family pinned by CONTENT (dimension and "
         "abelianness against a frozen table), with maximality COMPUTED from "
         "the dimension rather than read off a label.  THE HYPOTHESIS NEEDS "
         "NO MULTIPLICATION: three enumerated subspaces are not algebras and "
         "obey the same boundary, so the result holds for arbitrary "
         "subspaces.  TWO NAMED ROWS REFUTE THE WITHDRAWN DIAGNOSIS that "
         "commutativity is the obstruction -- a non-abelian composite at "
         "n = 2 and one non-abelian in both factors at n = 3 each omit the "
         "carrier.  SCOPED COROLLARY, with its fence executed: for a MAXIMAL "
         "abelian reference the conditional expectation of the carrier is a "
         "classical-classical state, exhibited separably; for a NON-maximal "
         "abelian reference the same formula returns the carrier unchanged, "
         "so the corollary is false outside its scope.  WHAT THIS DOES NOT "
         "SAY: anything about which composites physics supplies.  The "
         "condition is a saturation condition and whether any premise "
         "delivers it is chartered separately and NOT answered here."),
        {
            'boundary': 'rho_Omega in A (x) B  <=>  A = B = M_n',
            'support_dimensions': support_rows,
            'enumerated_rows': len(rows),
            'mismatches': mismatches,
            'non_algebra_subspaces_included': True,
            'auditor_rows': list(_AUDITOR_ROWS),
            'non_abelian_rows_omitting_carrier':
                sum(1 for r in rows
                    if not (r['A_abelian'] and r['B_abelian'])
                    and not r['carrier_in']),
            'corollary_dimensions': coroll_rows,
            'table': rows,
        },
        fails,
        3,
        (),
        ("none for the boundary: exact finite Gaussian-rational mathematics "
         "plus the named slice/support characterization, whose proof is in "
         "the module header.  The COROLLARY additionally uses Peres 1996, "
         "named in the header and not used by the boundary.",),
        ("proper pairs and non-algebra subspaces are enumerated alongside the "
         "maximal pair, so the predicate reads the model",
         "the rank routine is tested directly on dense inputs of known rank, "
         "including a complex one",
         "a product state has a one-dimensional support",
         "_is_abelian is controlled in both directions",
         "the corollary's fence is executed: outside its scope the same "
         "formula returns the carrier unchanged",
         "two named auditor rows refute the withdrawn diagnosis in-check",),
        ('T_composite_tensor_quotient', 'L_identity_carrier_vectorization',
         'ALL_POSITIVE_EFFECTS_REALIZABLE (named-open leaf)'),
        leg_count=counter,
        expected_legs=_EXPECTED_LEGS[_NAME],
    )


# ==========================================================================
# CHECK 2 -- the colour identification.
# ==========================================================================


def _su_gens(n: int) -> List[Mat]:
    """ANTI-Hermitian su(N) generators, exact over Q[i]."""
    out: List[Mat] = []
    for j in range(n):
        for k in range(j + 1, n):
            a = _zeros(n)
            a[j][k] = _ONE
            a[k][j] = _neg(_ONE)
            out.append(a)
            b = _zeros(n)
            b[j][k] = _I
            b[k][j] = _I
            out.append(b)
    for j in range(n - 1):
        d = _zeros(n)
        d[j][j] = _I
        d[j + 1][j + 1] = _neg(_I)
        out.append(d)
    return out


def _gauge_action(gen: Mat, n: int, conjugate: bool = True) -> Mat:
    """The fundamental (x) antifundamental action of record,
    L = g (x) I + I (x) conj(g).  ONE code path: the non-conjugated control
    is this same function with conjugate=False, so the control exercises the
    function under test rather than an inline rebuild."""
    idn = _eye(n)
    other = _conjm(gen) if conjugate else gen
    return _addm(_kron(gen, idn), _kron(idn, other))


def _singlet_proj(n: int) -> Mat:
    """TRANSCRIBED from gauge_invariant_record.py _singlet_proj.  Structurally
    pinned at the call site before comparison, so a transcription that simply
    delegated to the carrier constructor would not pass."""
    p = _zeros(n * n)
    v = _q(F(1, n))
    for i in range(n):
        for j in range(n):
            p[i * n + i][j * n + j] = v
    return p


def check_L_colour_record_is_the_identity_carrier() -> Dict[str, object]:
    """Tier 3, [P_structural_reading].  The banked colour record IS a carrier."""
    _NAME = 'check_L_colour_record_is_the_identity_carrier'
    fails: List[str] = []
    counter = [0, 0]
    ck = _ckr(fails, counter)

    ident_rows = []
    for n in (2, 3, 4):
        ps = _singlet_proj(n)
        car = _omega_density(n)

        # STRUCTURAL PIN on the transcription, BEFORE the comparison: the
        # support pattern and entry value are checked against the PUBLISHED
        # form of gauge_invariant_record._singlet_proj, so a transcription
        # that got the pattern or the normalization wrong is caught.
        # DISCLOSED LIMIT: this CANNOT distinguish a faithful transcription
        # from one that simply delegated to _omega_density, because the two
        # objects coincide -- which is exactly the result being reported.
        # Provenance of the transcription is carried by the header and by a
        # human reading, not by this leg.
        nz = [(i, j) for i in range(n * n) for j in range(n * n)
              if not _isz(ps[i][j])]
        ck(set(nz) == {(i * n + i, j * n + j)
                       for i in range(n) for j in range(n)},
           f"the transcribed singlet must have exactly the published support "
           f"pattern (N={n})")
        ck(all(ps[i][j] == _q(F(1, n)) for (i, j) in nz),
           f"every non-zero entry of the transcribed singlet must be 1/N "
           f"(N={n})")

        ck(_eqm(ps, car),
           f"the colour-singlet projector must equal the identity-carrier "
           f"density (N={n})")
        ck(_trace(ps) == _ONE, f"the record must have unit trace (N={n})")
        ck(_is_psd_hermitian(ps), f"the record must be a state (N={n})")

        def marginal(rho: Mat, keep_first: bool) -> Mat:
            out = _zeros(n)
            for i in range(n):
                for j in range(n):
                    s = _Z
                    for k in range(n):
                        s = _add(s, rho[i * n + k][j * n + k] if keep_first
                                 else rho[k * n + i][k * n + j])
                    out[i][j] = s
            return out

        ck(_eqm(marginal(ps, True), _scal(_q(F(1, n)), _eye(n))),
           f"the system marginal must be I/N -- flat Schmidt spectrum (N={n})")
        ck(_eqm(marginal(ps, False), _scal(_q(F(1, n)), _eye(n))),
           f"the reference marginal must be I/N (N={n})")
        # MARGINAL CONTROL: the carrier's two marginals coincide, so without a
        # state whose marginals DIFFER a wrong-leg trace would be invisible.
        skew = _zeros(n * n)
        skew[0 * n + 1][0 * n + 1] = _ONE
        ck(_eqm(marginal(skew, True), _unit(0, 0, n))
           and _eqm(marginal(skew, False), _unit(1, 1, n)),
           f"MARGINAL CONTROL: on |0,1> the two marginals must be the "
           f"distinct projectors |0><0| and |1><1|, pinning which factor each "
           f"leg traces (N={n})")
        ident_rows.append(n)
    ck(set(ident_rows) == {2, 3, 4},
       f"the identification must run at N = 2, 3, 4; got {sorted(ident_rows)}")

    # the gauge action must be non-trivial and generator-dependent, and the
    # singlet must be ANNIHILATED, not merely commuted with.
    gen_rows = set()
    for n in (2, 3):
        gens = _su_gens(n)
        ck(len(gens) == n * n - 1,
           f"su({n}) must have N^2-1 generators; got {len(gens)}")
        ck(_rank([_flat(g) for g in gens]) == n * n - 1,
           f"the su({n}) generators must be linearly independent and span "
           f"N^2-1 dimensions")
        for idx, gen in enumerate(gens):
            ck(_eqm(_dag(gen), _scal(_q(-1), gen)),
               f"su({n}) generator {idx} must be anti-Hermitian")
        acts = [_gauge_action(g, n) for g in gens]
        ck(all(not _iszm(a) for a in acts),
           f"no gauge action may be the ZERO operator (N={n}) -- a zero "
           f"action would satisfy every invariance leg vacuously")
        ck(len({tuple(_flat(a)) for a in acts}) == len(acts),
           f"the gauge actions must be GENERATOR-DEPENDENT and pairwise "
           f"distinct (N={n})")
        omega_vec = [_ONE if i // n == i % n else _Z for i in range(n * n)]
        ck(all(all(_isz(x) for x in _mv(a, omega_vec)) for a in acts),
           f"the carrier VECTOR must be ANNIHILATED by every generator "
           f"(N={n}) -- commutation with the projector is strictly weaker")
        ck(all(_iszm(_comm(_singlet_proj(n), a)) for a in acts),
           f"and the projector must commute with every action (N={n})")
        # DISCRIMINATING CONTROL: a state that is NOT invariant.
        not_inv = _kron(_unit(0, 0, n), _unit(0, 0, n))
        ck(any(not _iszm(_comm(not_inv, a)) for a in acts),
           f"a product record must FAIL invariance under the correct action "
           f"(N={n}), or the invariance leg accepts everything")
        gen_rows.add(n)
    ck(gen_rows == {2, 3},
       f"the gauge leg must run at N = 2, 3; got {sorted(gen_rows)}")

    # the conjugate on the reference leg is load-bearing -- SET-EXACT, both
    # inclusions, through the SAME function with the flag flipped.
    fail_idx = set()
    imag_idx = set()
    total = 0
    for n in (2, 3):
        for idx, gen in enumerate(_su_gens(n)):
            wrong = _gauge_action(gen, n, conjugate=False)
            key = (n, idx)
            total += 1
            if any(x[1] != 0 for r in gen for x in r):
                imag_idx.add(key)
            if not _iszm(_comm(_singlet_proj(n), wrong)):
                fail_idx.add(key)
    ck(fail_idx == imag_idx,
       f"the non-conjugated action must fail on EXACTLY the imaginary "
       f"generator family, both inclusions, computed as sets: "
       f"{len(fail_idx)} failures vs {len(imag_idx)} imaginary")
    ck(len(imag_idx) > 0 and len(imag_idx) < total,
       f"the imaginary family must be a PROPER non-empty subset, or the "
       f"set equality above is vacuous; got {len(imag_idx)} of {total}")

    return _result(
        _NAME,
        '[P_structural_reading | gauge-invariant = physical record, '
        'inherited from the no-B allocation]',
        ("THE BANKED COLOUR RECORD IS AN IDENTITY CARRIER.  The colour-singlet "
         "projector of SU(N) fundamental (x) antifundamental equals "
         "rho_Omega at N = 2, 3, 4 -- with the transcription pinned "
         "STRUCTURALLY by support pattern and entry value against the "
         "published form before the comparison, which catches a wrong "
         "pattern or normalization but, DISCLOSED, cannot distinguish a "
         "faithful transcription from a delegation to the carrier "
         "constructor, since the two objects coincide.  Both marginals are I/N.  The "
         "gauge actions are computed to be non-zero and pairwise distinct, "
         "the carrier VECTOR is ANNIHILATED by every generator (commutation "
         "with the projector being strictly weaker), and a product record is "
         "exhibited FAILING invariance.  The conjugate on the reference leg "
         "is load-bearing, computed SET-EXACTLY in both inclusions through "
         "the same function with the conjugation flag flipped: the "
         "non-conjugated action fails on exactly the imaginary generator "
         "family.  WHAT IS NOT CLAIMED: the uniqueness and "
         "commutant-dimension half is banked in gauge_invariant_record.py and "
         "cross-referenced, not recomputed, and the maximal entanglement of "
         "the singlet is already recorded there -- what is new here is the "
         "IDENTIFICATION of that object with rho_Omega.  This is an INSTANCE "
         "at one physical interface, not the generic system-plus-reference "
         "carrier the Born argument consumes, and the step from the instance "
         "to the generic carrier is exactly what stays open."),
        {
            'identification_dimensions': ident_rows,
            'gauge_dimensions': sorted(gen_rows),
            'nonconjugated_failure_set_equals_imaginary_family': True,
            'imaginary_generators': len(imag_idx),
            'generators_tested': total,
        },
        fails,
        3,
        (),
        ("gauge-invariant = physical/admissible record (the no-B allocation), "
         "inherited unchanged from check_T_only_gauge_invariant_sharp_colour_"
         "record_is_nonfactorizable_singlet_P and NOT re-argued here",
         "the step from this INSTANCE to a generic system-plus-reference "
         "carrier is NOT taken and is the open item",
         "the Schmidt decomposition, for reading a flat reduced spectrum as "
         "MAXIMAL entanglement",),
        ("a state whose two marginals differ pins which factor each leg "
         "traces",
         "a product record fails invariance under the correct action",
         "the gauge actions are non-zero and generator-dependent",
         "the non-conjugated failure set is computed set-exactly, both "
         "inclusions, and the imaginary family is a proper non-empty subset",),
        ('T_only_gauge_invariant_sharp_colour_record_is_nonfactorizable_'
         'singlet_P',
         'Theorem_R', 'L_identity_carrier_vectorization'),
        leg_count=counter,
        expected_legs=_EXPECTED_LEGS[_NAME],
    )


_CHECKS = {
    'check_L_identity_carrier_membership_boundary':
        check_L_identity_carrier_membership_boundary,
    'check_L_colour_record_is_the_identity_carrier':
        check_L_colour_record_is_the_identity_carrier,
}


def register(registry):
    """Entry point the bank calls.  Keys are the check_ names, so registry key
    == fn.__name__ == result['name'] for every entry."""
    registry.update(_CHECKS)
    return registry


def run_all():
    """Second gate only; the load-bearing cross-assert lives in _result()."""
    out = {}
    for n, fn in _CHECKS.items():
        r = fn()
        listed = len(r['fail_reasons'])
        counted = r['fail_count']
        if listed != counted:
            raise AssertionError(
                f"{n}: failure records disagree -- fail_reasons has {listed} "
                f"entries, the independent counter says {counted}")
        if n != r['name'] or _CHECKS[n].__name__ != n:
            raise AssertionError(
                f"registry key {n!r} must match the function name and the "
                f"result name")
        r['passed'] = (counted == 0)
        out[n] = r
    return out


if __name__ == '__main__':
    import sys
    bad = False
    for nm, res in run_all().items():
        print(res['name'], '::', res['epistemic'], '::',
              'PASS' if res['passed'] else 'FAIL')
        if not res['passed']:
            bad = True
            for f in res['fail_reasons'][:20]:
                print('  -', f)
    sys.exit(1 if bad else 0)
