"""
APF Initial Obstruction Classifier Theorem.

This module banks the universal-property layer above the Representation Descent Kernel.

Core idea:
    The APF obstruction object is not arbitrary bookkeeping.
    It is the free finite idempotent commutative obstruction classifier generated by the
    primitive APF descent-failure channels, subject to no-smuggling/promotion boundaries.

Universal statement:
    Any finite APF-compatible no-smuggling descent classifier factors uniquely through
    Obs_APF.

In symbols:
    LocalRep_APF --Obs_APF--> Obstr_APF --Phi_C--> C

where Phi_C is uniquely determined by the target classifier's treatment of primitive
failure channels.
"""

from __future__ import annotations

from dataclasses import dataclass
import itertools
from enum import Enum
from typing import Callable, Dict, FrozenSet, Iterable, Mapping, Optional, Tuple, Any

try:
    from apf.descent_obstruction_calculus import Obstruction, ObstructionObject
except Exception as exc:  # pragma: no cover
    raise ImportError(f"initial_obstruction_classifier requires descent_obstruction_calculus: {exc}") from exc


def _ok(name: str, *, status: str, summary: str, data: Optional[Mapping] = None,
        dependencies: Optional[Iterable[str]] = None) -> Dict:
    return {
        "name": name,
        "consistent": True,
        "status": status,
        "summary": summary,
        "data": dict(data or {}),
        "dependencies": list(dependencies or []),
    }


def _fail(name: str, *, status: str, summary: str, data: Optional[Mapping] = None,
          dependencies: Optional[Iterable[str]] = None) -> Dict:
    return {
        "name": name,
        "consistent": False,
        "status": status,
        "summary": summary,
        "data": dict(data or {}),
        "dependencies": list(dependencies or []),
    }


PRIMITIVE_CHANNELS: Tuple[Obstruction, ...] = tuple(ch for ch in Obstruction if ch != Obstruction.NONE)


@dataclass(frozen=True)
class FiniteIdempotentCommutativeMonoid:
    """Small target monoid used for finite classifier examples."""
    name: str
    elements: Tuple[Any, ...]
    zero: Any
    combine: Callable[[Any, Any], Any]

    def check_laws(self) -> Dict[str, bool]:
        elems = self.elements
        tests = {
            "zero_in_elements": self.zero in elems,
            "closure": all(self.combine(a, b) in elems for a in elems for b in elems),
            "left_identity": all(self.combine(self.zero, a) == a for a in elems),
            "right_identity": all(self.combine(a, self.zero) == a for a in elems),
            "commutative": all(self.combine(a, b) == self.combine(b, a) for a in elems for b in elems),
            "associative": all(
                self.combine(self.combine(a, b), c) == self.combine(a, self.combine(b, c))
                for a in elems for b in elems for c in elems
            ),
            "idempotent": all(self.combine(a, a) == a for a in elems),
        }
        return tests


@dataclass(frozen=True)
class CompatibleClassifier:
    """A finite APF-compatible classifier target.

    generator_map assigns each primitive APF obstruction channel to a target monoid element.
    The unique factorization map sends finite APF obstruction sets to the monoid fold of
    their generator images.
    """
    name: str
    target: FiniteIdempotentCommutativeMonoid
    generator_map: Mapping[Obstruction, Any]
    export_zero_value: Any
    provenance_fail_value: Any

    def phi(self, obs: ObstructionObject) -> Any:
        out = self.target.zero
        for ch in sorted(obs.channels, key=lambda c: c.value):
            out = self.target.combine(out, self.generator_map[ch])
        return out

    def classify_channels(self, channels: Iterable[Obstruction]) -> Any:
        return self.phi(ObstructionObject.of(*tuple(channels)))

    def compatible(self) -> bool:
        laws = self.target.check_laws()
        if not all(laws.values()):
            return False
        if set(self.generator_map.keys()) != set(PRIMITIVE_CHANNELS):
            return False
        if any(v not in self.target.elements for v in self.generator_map.values()):
            return False
        if self.phi(ObstructionObject.zero()) != self.export_zero_value:
            return False
        if self.generator_map[Obstruction.PROVENANCE_SMUGGLE] != self.provenance_fail_value:
            return False
        if self.provenance_fail_value == self.export_zero_value:
            return False
        return True


def boolean_failure_classifier() -> CompatibleClassifier:
    target = FiniteIdempotentCommutativeMonoid(
        name="BooleanFailure",
        elements=(False, True),
        zero=False,
        combine=lambda a, b: bool(a or b),
    )
    return CompatibleClassifier(
        name="boolean_failure",
        target=target,
        generator_map={ch: True for ch in PRIMITIVE_CHANNELS},
        export_zero_value=False,
        provenance_fail_value=True,
    )


def severity_classifier() -> CompatibleClassifier:
    # 0 exact, 1 ordinary repair/logistical, 2 substrate revision/structural, 3 provenance fail.
    target = FiniteIdempotentCommutativeMonoid(
        name="SeverityMax",
        elements=(0, 1, 2, 3),
        zero=0,
        combine=max,
    )
    mapping = {}
    for ch in PRIMITIVE_CHANNELS:
        if ch == Obstruction.PROVENANCE_SMUGGLE:
            mapping[ch] = 3
        elif ch in {
            Obstruction.POLARITY_MISSING,
            Obstruction.REVERSAL_MISSING,
            Obstruction.COMPLEX_ACTION_MISSING,
            Obstruction.NORM_MISSING,
        }:
            mapping[ch] = 2
        else:
            mapping[ch] = 1
    return CompatibleClassifier(
        name="severity",
        target=target,
        generator_map=mapping,
        export_zero_value=0,
        provenance_fail_value=3,
    )


def promotion_status_classifier() -> CompatibleClassifier:
    # Values ordered by max priority:
    # 0 export, 1 ordinary hold, 2 substrate revision hold, 3 provenance fail.
    target = FiniteIdempotentCommutativeMonoid(
        name="PromotionPriority",
        elements=("EXPORT_GLOBAL_P", "HOLD_ORDINARY_REPAIR_REQUIRED", "HOLD_SUBSTRATE_REVISION_REQUIRED", "FAIL_CLOSED_PROVENANCE"),
        zero="EXPORT_GLOBAL_P",
        combine=lambda a, b: max((a, b), key=lambda x: {
            "EXPORT_GLOBAL_P": 0,
            "HOLD_ORDINARY_REPAIR_REQUIRED": 1,
            "HOLD_SUBSTRATE_REVISION_REQUIRED": 2,
            "FAIL_CLOSED_PROVENANCE": 3,
        }[x]),
    )
    mapping = {}
    for ch in PRIMITIVE_CHANNELS:
        if ch == Obstruction.PROVENANCE_SMUGGLE:
            mapping[ch] = "FAIL_CLOSED_PROVENANCE"
        elif ch in {
            Obstruction.POLARITY_MISSING,
            Obstruction.REVERSAL_MISSING,
            Obstruction.COMPLEX_ACTION_MISSING,
            Obstruction.NORM_MISSING,
        }:
            mapping[ch] = "HOLD_SUBSTRATE_REVISION_REQUIRED"
        else:
            mapping[ch] = "HOLD_ORDINARY_REPAIR_REQUIRED"
    return CompatibleClassifier(
        name="promotion_status",
        target=target,
        generator_map=mapping,
        export_zero_value="EXPORT_GLOBAL_P",
        provenance_fail_value="FAIL_CLOSED_PROVENANCE",
    )


def all_channel_subsets() -> Tuple[Tuple[Obstruction, ...], ...]:
    channels = list(PRIMITIVE_CHANNELS)
    subsets = []
    for r in range(len(channels) + 1):
        for combo in itertools.combinations(channels, r):
            subsets.append(combo)
    return tuple(subsets)


def apf_free_union(obs_a: ObstructionObject, obs_b: ObstructionObject) -> ObstructionObject:
    return obs_a.combine(obs_b)


def classifier_preserves_union(classifier: CompatibleClassifier) -> bool:
    subsets = all_channel_subsets()
    for a in subsets:
        for b in subsets:
            oa = ObstructionObject.of(*a)
            ob = ObstructionObject.of(*b)
            lhs = classifier.phi(apf_free_union(oa, ob))
            rhs = classifier.target.combine(classifier.phi(oa), classifier.phi(ob))
            if lhs != rhs:
                return False
    return True


def unique_extension_holds(classifier: CompatibleClassifier) -> bool:
    """Finite uniqueness check.

    In a free idempotent commutative monoid, a homomorphism is determined by generator images.
    We verify this extension property by comparing phi(S) against the fold over singleton
    generator values for every subset S.
    """
    for subset in all_channel_subsets():
        obs = ObstructionObject.of(*subset)
        folded = classifier.target.zero
        for ch in sorted(subset, key=lambda c: c.value):
            folded = classifier.target.combine(folded, classifier.phi(ObstructionObject.of(ch)))
        if classifier.phi(obs) != folded:
            return False
    return True


def primitive_separation_table() -> Dict[str, Tuple[str, ...]]:
    """Show why each primitive channel is generated by a distinct APF descent axiom family."""
    return {
        "POLARITY_MISSING": ("substrate lacks polarity/orientation required by candidate representation",),
        "REVERSAL_MISSING": ("substrate lacks cost-preserving reversal/conjugation",),
        "COMPLEX_ACTION_MISSING": ("substrate lacks complex scalar action",),
        "NORM_MISSING": ("substrate lacks operator/C*-norm completion",),
        "EVALUATOR_MISSING": ("declared evaluator/route map absent",),
        "CAPACITY_OVERSPEND": ("capacity or cost budget exceeded",),
        "CODOMAIN_MISMATCH": ("codomain map or agreement absent",),
        "PROVENANCE_SMUGGLE": ("target value/posterior/output consumed as input",),
        "OVERLAP_INCOHERENCE": ("local sections fail overlap agreement",),
    }


def check_T_APF_obstruction_object_free_monoid_P() -> Dict:
    subsets = all_channel_subsets()
    tests = {
        "primitive_channel_count": len(PRIMITIVE_CHANNELS) == 9,
        "subset_count": len(subsets) == 2 ** len(PRIMITIVE_CHANNELS),
        "zero_empty": ObstructionObject.zero().is_zero,
        "union_idempotent": all(
            apf_free_union(ObstructionObject.of(*s), ObstructionObject.of(*s)) == ObstructionObject.of(*s)
            for s in subsets
        ),
        "union_commutative": all(
            apf_free_union(ObstructionObject.of(*a), ObstructionObject.of(*b)) ==
            apf_free_union(ObstructionObject.of(*b), ObstructionObject.of(*a))
            for a in subsets[:64] for b in subsets[:64]
        ),
    }
    if all(tests.values()):
        return _ok(
            "check_T_APF_obstruction_object_free_monoid_P",
            status="P_universal",
            summary="APF obstruction objects form the finite free idempotent commutative monoid generated by primitive descent-failure channels.",
            data={"tests": tests, "channels": [ch.value for ch in PRIMITIVE_CHANNELS]},
        )
    return _fail("check_T_APF_obstruction_object_free_monoid_P", status="FAIL", summary="Free obstruction monoid check failed", data=tests)


def check_T_compatible_classifier_targets_P() -> Dict:
    classifiers = [boolean_failure_classifier(), severity_classifier(), promotion_status_classifier()]
    results = {
        c.name: {
            "compatible": c.compatible(),
            "laws": c.target.check_laws(),
            "export_zero": c.phi(ObstructionObject.zero()),
            "provenance_singleton": c.phi(ObstructionObject.of(Obstruction.PROVENANCE_SMUGGLE)),
        }
        for c in classifiers
    }
    tests = {
        "all_compatible": all(r["compatible"] for r in results.values()),
        "all_have_zero_export": all(r["export_zero"] in (False, 0, "EXPORT_GLOBAL_P") for r in results.values()),
        "all_provenance_nonzero": all(r["provenance_singleton"] not in (False, 0, "EXPORT_GLOBAL_P") for r in results.values()),
    }
    if all(tests.values()):
        return _ok(
            "check_T_compatible_classifier_targets_P",
            status="P_universal",
            summary="Example target classifiers satisfy finite no-smuggling classifier compatibility.",
            data={"results": results, "tests": tests},
            dependencies=["check_T_APF_obstruction_object_free_monoid_P"],
        )
    return _fail("check_T_compatible_classifier_targets_P", status="FAIL", summary="Compatible classifier target check failed", data={"results": results, "tests": tests})


def check_T_factorization_through_APF_Obs_P() -> Dict:
    classifiers = [boolean_failure_classifier(), severity_classifier(), promotion_status_classifier()]
    tests = {}
    details = {}
    sample_obs = [
        ObstructionObject.zero(),
        ObstructionObject.of(Obstruction.CAPACITY_OVERSPEND),
        ObstructionObject.of(Obstruction.EVALUATOR_MISSING, Obstruction.CODOMAIN_MISMATCH),
        ObstructionObject.of(Obstruction.REVERSAL_MISSING, Obstruction.COMPLEX_ACTION_MISSING, Obstruction.NORM_MISSING),
        ObstructionObject.of(Obstruction.PROVENANCE_SMUGGLE, Obstruction.CODOMAIN_MISMATCH),
    ]
    for classifier in classifiers:
        tests[f"{classifier.name}_preserves_union"] = classifier_preserves_union(classifier)
        tests[f"{classifier.name}_unique_extension"] = unique_extension_holds(classifier)
        details[classifier.name] = {
            "sample_values": [
                {"obs": obs.names(), "phi": classifier.phi(obs)}
                for obs in sample_obs
            ]
        }
    if all(tests.values()):
        return _ok(
            "check_T_factorization_through_APF_Obs_P",
            status="P_universal",
            summary="Compatible target classifiers factor through Obs_APF by unique generator-determined homomorphisms.",
            data={"tests": tests, "details": details},
            dependencies=["check_T_compatible_classifier_targets_P"],
        )
    return _fail("check_T_factorization_through_APF_Obs_P", status="FAIL", summary="Factorization check failed", data={"tests": tests, "details": details})


def check_T_primitive_failure_generation_P() -> Dict:
    table = primitive_separation_table()
    tests = {
        "all_channels_accounted": set(table.keys()) == {ch.value for ch in PRIMITIVE_CHANNELS},
        "no_empty_explanations": all(len(v) >= 1 and all(x for x in v) for v in table.values()),
        "provenance_distinct": "target" in table["PROVENANCE_SMUGGLE"][0] or "posterior" in table["PROVENANCE_SMUGGLE"][0],
        "cstar_structural_distinct": all(
            key in table for key in ["REVERSAL_MISSING", "COMPLEX_ACTION_MISSING", "NORM_MISSING"]
        ),
    }
    if all(tests.values()):
        return _ok(
            "check_T_primitive_failure_generation_P",
            status="P_universal",
            summary="Primitive obstruction channels are generated by distinct APF descent-failure axiom families.",
            data={"table": table, "tests": tests},
            dependencies=["check_T_APF_obstruction_object_free_monoid_P"],
        )
    return _fail("check_T_primitive_failure_generation_P", status="FAIL", summary="Primitive failure generation failed", data={"table": table, "tests": tests})


def check_T_initiality_minimality_P() -> Dict:
    # Minimality: removing any primitive channel collapses at least one distinct descent failure.
    table = primitive_separation_table()
    removal_witnesses = {}
    for ch in PRIMITIVE_CHANNELS:
        reduced = [x for x in PRIMITIVE_CHANNELS if x != ch]
        # The singleton obstruction for ch cannot be represented in the reduced generator set.
        removal_witnesses[ch.value] = {
            "removed_channel": ch.value,
            "remaining_count": len(reduced),
            "lost_failure_family": table[ch.value][0],
            "singleton_lost": ch not in reduced,
        }
    tests = {
        "each_channel_has_removal_witness": len(removal_witnesses) == len(PRIMITIVE_CHANNELS),
        "every_removal_loses_singleton": all(w["singleton_lost"] for w in removal_witnesses.values()),
        "minimal_count": len(PRIMITIVE_CHANNELS) == 9,
    }
    if all(tests.values()):
        return _ok(
            "check_T_initiality_minimality_P",
            status="P_universal",
            summary="The primitive generator set is minimal: deleting any channel loses a distinct APF failure family.",
            data={"removal_witnesses": removal_witnesses, "tests": tests},
            dependencies=["check_T_primitive_failure_generation_P", "check_T_factorization_through_APF_Obs_P"],
        )
    return _fail("check_T_initiality_minimality_P", status="FAIL", summary="Initiality/minimality failed", data={"tests": tests, "removal_witnesses": removal_witnesses})


def check_T_no_smuggling_universal_boundary_P() -> Dict:
    classifier = promotion_status_classifier()
    provenance = ObstructionObject.of(Obstruction.PROVENANCE_SMUGGLE)
    provenance_plus_exact = ObstructionObject.of(Obstruction.PROVENANCE_SMUGGLE, Obstruction.CODOMAIN_MISMATCH)
    zero = ObstructionObject.zero()
    tests = {
        "zero_exports": classifier.phi(zero) == "EXPORT_GLOBAL_P",
        "provenance_fails_closed": classifier.phi(provenance) == "FAIL_CLOSED_PROVENANCE",
        "provenance_dominates_combo": classifier.phi(provenance_plus_exact) == "FAIL_CLOSED_PROVENANCE",
        "provenance_not_equal_export": classifier.phi(provenance) != classifier.phi(zero),
    }
    if all(tests.values()):
        return _ok(
            "check_T_no_smuggling_universal_boundary_P",
            status="P_audit",
            summary="Universal classifier boundary preserves no-smuggling: provenance failure cannot factor to export or ordinary repair.",
            data={"tests": tests},
            dependencies=["check_T_factorization_through_APF_Obs_P"],
        )
    return _fail("check_T_no_smuggling_universal_boundary_P", status="FAIL", summary="No-smuggling universal boundary failed", data=tests)


def check_T_initial_obstruction_classifier_theorem_P() -> Dict:
    subchecks = [
        check_T_APF_obstruction_object_free_monoid_P(),
        check_T_compatible_classifier_targets_P(),
        check_T_factorization_through_APF_Obs_P(),
        check_T_primitive_failure_generation_P(),
        check_T_initiality_minimality_P(),
        check_T_no_smuggling_universal_boundary_P(),
    ]
    ok = all(x["consistent"] for x in subchecks)
    if ok:
        return _ok(
            "check_T_initial_obstruction_classifier_theorem_P",
            status="P_universal",
            summary="Obs_APF is the initial/minimal finite no-smuggling obstruction classifier for APF representation descent.",
            data={
                "universal_property": "Any finite APF-compatible no-smuggling descent classifier factors uniquely through Obs_APF.",
                "free_generators": [ch.value for ch in PRIMITIVE_CHANNELS],
                "minimality": "Deleting any primitive channel loses a distinct APF descent-failure family.",
                "subchecks": [x["name"] for x in subchecks],
            },
            dependencies=[x["name"] for x in subchecks],
        )
    return _fail(
        "check_T_initial_obstruction_classifier_theorem_P",
        status="FAIL",
        summary="Initial obstruction classifier theorem failed.",
        data={"subchecks": subchecks},
    )


CHECKS = {
    "check_T_APF_obstruction_object_free_monoid_P": check_T_APF_obstruction_object_free_monoid_P,
    "check_T_compatible_classifier_targets_P": check_T_compatible_classifier_targets_P,
    "check_T_factorization_through_APF_Obs_P": check_T_factorization_through_APF_Obs_P,
    "check_T_primitive_failure_generation_P": check_T_primitive_failure_generation_P,
    "check_T_initiality_minimality_P": check_T_initiality_minimality_P,
    "check_T_no_smuggling_universal_boundary_P": check_T_no_smuggling_universal_boundary_P,
    "check_T_initial_obstruction_classifier_theorem_P": check_T_initial_obstruction_classifier_theorem_P,
}


def register(registry=None):
    if registry is None:
        return CHECKS
    if hasattr(registry, "update"):
        registry.update(CHECKS)
        return registry
    for name, fn in CHECKS.items():
        if hasattr(registry, "register"):
            registry.register(name, fn)
        elif hasattr(registry, "add"):
            registry.add(name, fn)
        else:
            raise TypeError("Unsupported registry type for initial_obstruction_classifier.register")
    return registry


def run_all() -> Dict[str, Dict]:
    return {name: fn() for name, fn in CHECKS.items()}


if __name__ == "__main__":
    import json
    results = run_all()
    print(json.dumps(results, indent=2, sort_keys=True))
    raise SystemExit(0 if all(x.get("consistent") for x in results.values()) else 1)
