#!/usr/bin/env python3
"""Integrate the Held-holonomy certificate into the APF registry and IE surface.

This is an idempotent, assertion-guarded landing helper for v24.3.429.  It edits
only the canonical registry/version/census surfaces.  Reviewer artifacts are
regenerated by the calling workflow after these guarded replacements succeed.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def _write(rel: str, text: str) -> None:
    path = ROOT / rel
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count == 0 and new in text:
        return text
    if count != 1:
        raise RuntimeError(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


def patch_manifest() -> None:
    rel = "apf/_module_manifest.py"
    text = _read(rel)
    text = _replace_once(
        text,
        '    "apf.continuation_tesseract_bridge",  # v24.3.428: 4 conditional HOC/positivity checks\n',
        '    "apf.continuation_tesseract_bridge",  # v24.3.428: 4 conditional HOC/positivity checks\n'
        '    "apf.held_holonomy",  # v24.3.429: 10 Held relative-loop holonomy certificates\n',
        "bank module insertion",
    )
    text = _replace_once(
        text,
        "    'apf.continuation_tesseract_bridge': 'extension',\n",
        "    'apf.continuation_tesseract_bridge': 'extension',\n"
        "    'apf.held_holonomy': 'extension',\n",
        "module-type insertion",
    )
    text = _replace_once(
        text,
        "# 251 modules with register(registry) populating apf.bank.REGISTRY.\n",
        "# 252 modules with register(registry) populating apf.bank.REGISTRY.\n",
        "bank module count",
    )
    marker = "EXPECTED_REGISTRY_SIZE: int = 3928"
    if "EXPECTED_REGISTRY_SIZE: int = 3938" not in text:
        if text.count(marker) != 1:
            raise RuntimeError("expected-size marker missing or duplicated")
        text = text.replace(
            marker,
            "# +10 v24.3.429 HELD RELATIVE-LOOP HOLONOMY CERTIFICATE "
            "(2026-07-20): exact finite H1-H7 schemas, negative controls, "
            "SAT bypass disposition, and no-positivity-cycle tripwire; one "
            "non-exporting IE row; physical premises remain named.\n"
            "EXPECTED_REGISTRY_SIZE: int = 3938",
            1,
        )
    _write(rel, text)


def patch_setup() -> None:
    rel = "setup.py"
    text = _read(rel)
    text = _replace_once(
        text,
        "    version='24.3.428',\n",
        "    version='24.3.429',\n",
        "setup version",
    )
    _write(rel, text)


def patch_wall_shadow() -> None:
    rel = "apf/ie_wall_shadow_census.py"
    text = _read(rel)
    text = _replace_once(
        text,
        '    "quantum:zipper_root_physicality_gate": "self_certifying_closure",\n',
        '    "quantum:zipper_root_physicality_gate": "self_certifying_closure",\n'
        '    # Held holonomy v24.3.429: finite certificate passes; physical premises named.\n'
        '    "quantum:held_holonomy_conditional_certificate": "self_certifying_closure",\n',
        "wall-shadow disposition",
    )
    _write(rel, text)


def patch_full_surface_census() -> None:
    rel = "apf/ie_export_core_census.py"
    text = _read(rel)
    replacements = (
        ("all 207 pinned", "all 208 pinned", "full-surface header count"),
        ('check(rep["n_export_inputs"] == 207,', 'check(rep["n_export_inputs"] == 208,',
         "full-surface assertion"),
        ("full scope: 207 pinned inputs walked", "full scope: 208 pinned inputs walked",
         "full-surface failure text"),
        ("machine-verified: 207 inputs;", "machine-verified: 208 inputs;",
         "full-surface key result"),
        ("all 200 pinned atlas", "all 208 pinned atlas", "full-surface summary"),
        ("0. SCOPE: all 200 pinned inputs walked", "0. SCOPE: all 208 pinned inputs walked",
         "full-surface docstring scope"),
    )
    for old, new, label in replacements:
        text = _replace_once(text, old, new, label)
    _write(rel, text)


def main() -> int:
    patch_manifest()
    patch_setup()
    patch_wall_shadow()
    patch_full_surface_census()
    print("Held-holonomy registry integration patches applied")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
